#!/usr/bin/python

"""
Given an integer, convert it to a roman numeral.

Input is guaranteed to be within the range from 1 to 3999.
"""

"""
Numeral	Value
I	1
IV  4
V	5
IX  9
X	10
XL  40
L	50
XC  90
C	100
CD  400
D	500
CM  900
M	1000
"""

class Solution:
    def intToRoman(self, num):
        strs = ['M', 'CM', 'D', 'CD', 'C', 'XC', 'L', 'XL', 'X', 'IX', 'V',
                'IV', 'I']
        nums = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1]
        roman = ""
        for index, item in enumerate(nums):
            while num >= item:
                roman += strs[index]
                num -= item
            if num == 0:
                return roman


solution = Solution()
print(solution.intToRoman(1245))

