#!/usr/bin/python

"""
Given an integer, write a function to determine if it is a power of two.
"""


class Solution:
    def isPowerOfTwo(self, n):
        if n <= 0:
            return False

        # 4 is a power of 2, 6 is not. 6 / 2 = 3, 3 / 2 = decimal
        while n % 2 == 0:
            n = n / 2

        return n == 1

solution = Solution()
print(solution.isPowerOfTwo(6))
print(solution.isPowerOfTwo(16))
print(solution.isPowerOfTwo(-1))